version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  producer:
    build: ./producer
    container_name: recipe_producer
    depends_on:
      - kafka
    volumes:
      - ./dataset:/app/dataset
    environment:
      KAFKA_BROKER: 'kafka:9092'
      DATASET_PATH: '/app/dataset/recipes_data.csv'
      KAFKA_TOPIC: 'recipes'
      MAX_ROWS_TO_SEND: 30005 # Sesuaikan dengan jumlah baris yang ingin dikirim

  consumer:
    build: ./consumer
    container_name: recipe_consumer
    depends_on:
      - kafka
    volumes:
      - ./data_batches:/app/data_batches
    environment:
      KAFKA_BROKER: 'kafka:9092'
      KAFKA_TOPIC: 'recipes'
      GROUP_ID: 'recipe_consumer_group'
      BATCH_SIZE: 10000
      OUTPUT_DIR: '/app/data_batches'
      NUM_BATCHES_TO_WRITE: 3

  spark-trainer:
    build: ./spark_trainer
    container_name: recipe_spark_trainer
    depends_on:
      - consumer
    volumes:
      - ./data_batches:/app/data_batches
      - ./spark_models:/app/spark_models
    environment:
      SPARK_MASTER_URL: "local[*]"
      APP_NAME: "RecipeModelTrainer"
      DATA_BATCHES_DIR: "/app/data_batches"
      MODELS_DIR: "/app/spark_models"
    command: >
      sh -c "
        echo 'Waiting for data batches to be created...'
        while [ ! -f /app/data_batches/batch_2.csv ]; do sleep 5; done;
        echo 'Batches found. Starting Spark training...'
        python spark_trainer.py
      "

  api:
    build: ./api
    container_name: recipe_api
    ports:
      - "5001:5001"
    depends_on:
      - spark-trainer
    volumes:
      - ./spark_models:/app/spark_models
    environment:
      MODELS_DIR: "/app/spark_models"
    command: >
      sh -c "
        echo 'Waiting for models to be trained...'
        while [ ! -d /app/spark_models/model_3_kmeans ]; do sleep 10; done;
        echo 'Models found. Starting API server with Gunicorn...'
        gunicorn --bind 0.0.0.0:5001 api:app
      "

volumes:
  kafka_data:
